
# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(fluidPage(

  # Application title
  titlePanel("Defensins Sequence Space"),
  wellPanel(
    div(class="header",
        p("This webtool indicates whether a given sequence is a cis-defensin or trans-defensin, and maps
          its location in sequence space. It also determines which cluster it falls into within the sequence space,
          and lists the sequences closest to it in the local sequence space."),
        p("All of the calculations and plots generated by this webtool can also be generated using the underlying ",
          a(href="https://github.com/TS404/DefSpace","DefSpace R package"))
        )
  ),
  
  # Inputs section
  sidebarLayout(

    # Select superfamily
    mainPanel(
      h3("Inputs"),
      p("Input the query sequence to locate in the defensin sequence space. Since the defensins consist
        of two independent superfamilies, indicate whether it is a cis-defensin of trans-defnesin (if known)"),
      wellPanel(
        textInput("query_sequence",
                  label       = "Input query sequence",
                  placeholder = "Amino acid sequence",
                  value       = "RECKTESNTFPGICITKPPCRKACISEKFTDGHCSKILRRCLCTKPC"),
        selectInput("query_type",
                    label   = "Superfamily (if known)",
                    choices  = c("unknown","cis-Defensin","trans-Defensin"),
                    selected = "unknown"),
        actionButton("button", "Calculate")
      )
    ),

    
    # Outputs section 
    mainPanel(
      
      # Display summary text
      h3("Results summary"),
      textOutput("report"),
      textOutput("report2"),
      textOutput("report3"),
      
      # Display fasta alignment
      h3("Nearest neighbours"),
      p("These are the sequences that are closest to the query sequence within the sequence space."),
      numericInput("return_nearest","Number of nearest neighbours",20,min = 2,max=1000),
      htmlOutput("fasta",style = "font-family:Courier New ; min-width:500px"),
      
      plotOutput("mainplot")
    )
  )
))
